version: '3.9'

services:
  db:
    build: db
    environment:
      - POSTGRES_DB=toxic
      - POSTGRES_USER=toxic
      - POSTGRES_PASSWORD=toxic
    ports:
      - 127.0.0.1:30131:5432/tcp
    healthcheck:
      test: ps -p 1 -o comm= | grep postgres
      interval: 1s
      timeout: 5s
      retries: 20
