# DO NOT EDIT.  The code was generated by https://github.com/slasyz/op util.
##*********************
##* Makefile commands *
##*********************
##

export SHELL := /bin/bash
export PYTHON_INTERPRETER := $(shell ( ls ./venv/Scripts/python.exe ./venv/bin/python 2> /dev/null || echo python ) | head -n 1)

.DEFAULT_GOAL := help


.PHONY: help
help:           ## show this help
	@sed -nE '/@sed/!s/##\s?//p' Makefile


.PHONY: lint
lint:           ## run linter with less strict checks
lint: DISABLE=invalid-name,unused-argument
lint: pylint

.PHONY: lint.all
lint.all:       ## run linter with all usable checks
lint.all: pylint


.PHONY: pylint
pylint:         ## run pylint (with disabled checks specified in $DISABLE variable)
	$(PYTHON_INTERPRETER) -m pylint ./main.py ./toxic --rcfile="./pylintrc" --disable="$(DISABLE)"


.PHONY: test
test:           ## run unit tests
	$(PYTHON_INTERPRETER) -m pytest tests/unit

.PHONY: test.all
test.all:       ## run all tests, should run from container
	$(PYTHON_INTERPRETER) -m pytest tests


.PHONY: deps
deps:           ## install all dependencies from requirements.txt
	$(PYTHON_INTERPRETER) -m pip install -r requirements.txt

.PHONY: venv
venv:           ## create virtual environment and install all dependencies
	virtualenv venv -p python3
	$(MAKE) deps

.PHONY: run
run:            ## start bot in foreground
	$(PYTHON_INTERPRETER) ./main.py
