short_name = 'toxic'
long_name = 'slasyz/toxicbot'
language = 'python'
config = 'json'

project_id = 1
environments = ['local', 'prod']

app_second = true  # TODO: maybe replace with prometheus
database = true
