version: '3.9'

services:
  app:
    image: slasyz/toxicbot/app:latest
    deploy:
      restart_policy:
        max_attempts: 5
        window: 5s
    networks:
      - main
    depends_on:
      - db

  db:
    image: slasyz/toxicbot/db:latest
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_username
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - postgres_username
      - postgres_password
      - postgres_database
    networks:
      - main

networks:
  main:

volumes:
  postgres_data:

secrets:
  postgres_username:
    external: true
  postgres_password:
    external: true
  postgres_database:
    external: true
  telegram_token:
    external: true
