version: '3.9'

services:
  app:
    ports:
      - 30110:8000
  db:
    ports:
      - 30111:5432

secrets:
  postgres_username:
    external: true
    name: toxic_local_postgres_username
  postgres_password:
    external: true
    name: toxic_local_postgres_password
  postgres_database:
    external: true
    name: toxic_local_postgres_database
  telegram_token:
    external: true
    name: toxic_local_telegram_token
