version: '3.9'

services:
  app:
    volumes:
      - type: bind
        source: /etc/toxic/config.json
        target: /etc/toxic/config.json
        read_only: true
    ports:
      - target: 8000
        published: 30120
        protocol: tcp
      - target: 8001
        published: 30122
        protocol: tcp
  db:
    ports:
      - target: 5432
        published: 30121
        protocol: tcp
