version: '3.9'

services:
  app:
    volumes:
      - type: bind
        source: /etc/toxic/config.json
        target: /etc/toxic/config.json
        read_only: true
    ports:
      - target: 8000
        published: 30120
        protocol: tcp
  db:
    ports:
      - target: 5432
        published: 30121
        protocol: tcp

secrets:
  postgres_username:
    external: true
    name: toxic_prod_postgres_username
  postgres_password:
    external: true
    name: toxic_prod_postgres_password
  postgres_database:
    external: true
    name: toxic_prod_postgres_database
