version: '3.9'

services:
  app:
    volumes:
      - type: bind
        source: /etc/toxic/config.json
        target: /etc/toxic/config.json
        read_only: true
    ports:
      - 127.0.0.1:30110:8000/tcp
      - 127.0.0.1:30112:8001/tcp
  db:
    volumes:
      - type: bind
        source: ../config.json
        target: /etc/toxic/config.json
        read_only: true
    ports:
      - 127.0.0.1:30111:5432/tcp
