- name: Copy files
  hosts: hetzner-1
  vars:
    project_dir: "{{ ansible_env.HOME }}/deployments/toxic"
    logs_prefix: "{{ ansible_env.HOME }}/logs/toxic"
  tasks:
    - name: Copy sources
      synchronize:
        src: ../toxic/
        dest: "{{ project_dir }}/toxic/"
    - name: Copy main.py
      copy:
        src: ../main.py
        dest: "{{ project_dir }}/main.py"
    - name: Copy resources
      synchronize:
        src: ../resources/
        dest: "{{ project_dir }}/resources/"
    - name: Copy config
      copy:
        src: ../config.json
        dest: "{{ project_dir }}/config.json"
    - name: Copy main systemd service
      template:
        src: ../systemd/toxic-main.service
        dest: ~/.config/systemd/user/toxic-main.service
        mode: 0644
    - name: Copy server systemd service
      template:
        src: ../systemd/toxic-server.service
        dest: ~/.config/systemd/user/toxic-server.service
        mode: 0644
    - name: Copy requirements.txt
      copy:
        src: ../requirements.txt
        dest: "{{ project_dir }}/requirements.txt"
    - name: Copy Makefile
      copy:
        src: ../Makefile
        dest: "{{ project_dir }}/Makefile"

    - name: Install dependencies
      make:
        chdir: "{{ project_dir }}"
        target: deps

    - name: Restart main service
      systemd:
        name: toxic-main
        state: restarted
        daemon_reload: yes
        scope: user
        enabled: true
    - name: Restart server service
      systemd:
        name: toxic-server
        state: restarted
        daemon_reload: yes
        scope: user
        enabled: true
