- name: Prepare things
  hosts: hetzner-1
  vars:
    project_dir: "{{ ansible_env.HOME }}/deployments/toxic"
  vars_prompt:
    - name: "postgres_password"
      prompt: "Enter postgres password"
      private: yes
  tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ project_dir }}"
    - name: Create postgres user
      become: yes
      become_user: postgres
      postgresql_user:
        name: toxic
        password: "{{ postgres_password }}"
    - name: Create postgres database
      become: yes
      become_user: postgres
      postgresql_db:
        name: toxic
        owner: toxic
