##
##*************************************
##* Makefile commands for development *
##*************************************
##


.PHONY: backup.host
backup.host:    ## create remote database (running on host OS) backup in local directory
	ssh sl@slasyz.ru 'pg_dump --data-only --inserts -h localhost -U toxicuser -d toxicdb | gzip' > "$(BACKUP_FILENAME)-host.sql.gz"
	du -sh ./backups/*


.PHONY: lint
lint:           ## run linter with less strict checks
lint: DISABLE=invalid-name,unused-argument
lint: pylint

.PHONY: lint.all
lint.all:       ## run linter with all usable checks
lint.all: pylint


.PHONY: port
port:           ## run port forwarding to open Flask server locally and connect to prod database
	@echo "http://localhost:30120/messages"
	@echo "psql -h localhost -p 30121 -U toxic -d toxic"
	@ssh -L 30120:localhost:30120 -L 30121:localhost:30121 sl@slasyz.ru "sleep infinity"

.PHONY: pylint
pylint:         ## run pylint (with disabled checks specified in $DISABLE variable)
	cd ..; ./ToxicTgBot/$(PYTHON_INTERPRETER) -m pylint ./ToxicTgBot --rcfile="./ToxicTgBot/pylintrc" --disable="$(DISABLE)"


.PHONY: test
test:           ## run unit tests
	$(PYTHON_INTERPRETER) -m pytest tests/unit

.PHONY: test.all
test.all:       ## run all tests
	$(PYTHON_INTERPRETER) -m pytest tests
