name: Linter and tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install virtualenv
      run: sudo apt-get install virtualenv
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make venv
    - name: Run tests
      run: |
        make test.all
    - name: Run linter
      run: |
        make lint
